// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.

import 'package:efs_misr/Features/Home/data/models/supadart_header.dart';

class Assets implements SupadartClass<Assets> {
  final BigInt id;
  final BigInt? barcode;
  final String? name;
  final String? model;
  final String? place;
  final BigInt? Branch;
  final DateTime createdAt;
  final BigInt? tickets;

  const Assets({
    required this.id,
    this.barcode,
    this.name,
    this.model,
    this.place,
    this.Branch,
    required this.createdAt,
    this.tickets,
  });

  static String get table_name => 'assets';
  static String get c_id => 'id';
  static String get c_barcode => 'barcode';
  static String get c_name => 'name';
  static String get c_model => 'model';
  static String get c_place => 'place';
  static String get c_Branch => 'Branch';
  static String get c_createdAt => 'created_at';
  static String get c_tickets => 'tickets';

  static List<Assets> converter(List<Map<String, dynamic>> data) {
    return data.map(Assets.fromJson).toList();
  }

  static Assets converterSingle(Map<String, dynamic> data) {
    return Assets.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    BigInt? id,
    BigInt? barcode,
    String? name,
    String? model,
    String? place,
    BigInt? Branch,
    DateTime? createdAt,
    BigInt? tickets,
  }) {
    return {
      if (id != null) 'id': id.toString(),
      if (barcode != null) 'barcode': barcode.toString(),
      if (name != null) 'name': name,
      if (model != null) 'model': model,
      if (place != null) 'place': place,
      if (Branch != null) 'Branch': Branch.toString(),
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (tickets != null) 'tickets': tickets.toString(),
    };
  }

  static Map<String, dynamic> insert({
    BigInt? id,
    BigInt? barcode,
    String? name,
    String? model,
    String? place,
    BigInt? Branch,
    DateTime? createdAt,
    BigInt? tickets,
  }) {
    return _generateMap(
      id: id,
      barcode: barcode,
      name: name,
      model: model,
      place: place,
      Branch: Branch,
      createdAt: createdAt,
      tickets: tickets,
    );
  }

  static Map<String, dynamic> update({
    BigInt? id,
    BigInt? barcode,
    String? name,
    String? model,
    String? place,
    BigInt? Branch,
    DateTime? createdAt,
    BigInt? tickets,
  }) {
    return _generateMap(
      id: id,
      barcode: barcode,
      name: name,
      model: model,
      place: place,
      Branch: Branch,
      createdAt: createdAt,
      tickets: tickets,
    );
  }

  factory Assets.fromJson(Map<String, dynamic> jsonn) {
    return Assets(
      id: jsonn['id'] != null
          ? BigInt.parse(jsonn['id'].toString())
          : BigInt.from(0),
      barcode: jsonn['barcode'] != null
          ? BigInt.parse(jsonn['barcode'].toString())
          : null,
      name: jsonn['name'] != null ? jsonn['name'].toString() : null,
      model: jsonn['model'] != null ? jsonn['model'].toString() : null,
      place: jsonn['place'] != null ? jsonn['place'].toString() : null,
      Branch: jsonn['Branch'] != null
          ? BigInt.parse(jsonn['Branch'].toString())
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      tickets: jsonn['tickets'] != null
          ? BigInt.parse(jsonn['tickets'].toString())
          : null,
    );
  }

  static Object New({
    BigInt? id,
    BigInt? barcode,
    String? name,
    String? model,
    String? place,
    BigInt? Branch,
    DateTime? createdAt,
    BigInt? tickets,
  }) {
    return {
      if (id != null) 'id': id,
      if (barcode != null) 'barcode': barcode,
      if (name != null) 'name': name,
      if (model != null) 'model': model,
      if (place != null) 'place': place,
      if (Branch != null) 'Branch': Branch,
      if (createdAt != null) 'created_at': createdAt,
      if (tickets != null) 'tickets': tickets,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      barcode: barcode,
      name: name,
      model: model,
      place: place,
      Branch: Branch,
      createdAt: createdAt,
      tickets: tickets,
    );
  }

  static const _unset = Object();
  Assets copyWith({
    Object? id = _unset,
    Object? barcode = _unset,
    Object? name = _unset,
    Object? model = _unset,
    Object? place = _unset,
    Object? Branch = _unset,
    Object? createdAt = _unset,
    Object? tickets = _unset,
  }) {
    return Assets(
      id: id == _unset ? this.id : id as BigInt,
      barcode: barcode == _unset ? this.barcode : barcode as BigInt?,
      name: name == _unset ? this.name : name as String?,
      model: model == _unset ? this.model : model as String?,
      place: place == _unset ? this.place : place as String?,
      Branch: Branch == _unset ? this.Branch : Branch as BigInt?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
      tickets: tickets == _unset ? this.tickets : tickets as BigInt?,
    );
  }
}
