// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Area implements SupadartClass<Area> {
  final BigInt id;
  final String? name;
  final DateTime createdAt;

  const Area({
    required this.id,
    this.name,
    required this.createdAt,
  });

  static String get table_name => 'area';
  static String get c_id => 'id';
  static String get c_name => 'name';
  static String get c_createdAt => 'created_at';

  static List<Area> converter(List<Map<String, dynamic>> data) {
    return data.map(Area.fromJson).toList();
  }

  static Area converterSingle(Map<String, dynamic> data) {
    return Area.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    BigInt? id,
    String? name,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id.toString(),
      if (name != null) 'name': name,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    BigInt? id,
    String? name,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      name: name,
      createdAt: createdAt,
    );
  }

  static Map<String, dynamic> update({
    BigInt? id,
    String? name,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      name: name,
      createdAt: createdAt,
    );
  }

  factory Area.fromJson(Map<String, dynamic> jsonn) {

    return Area(
      id: jsonn['id'] != null
          ? BigInt.parse(jsonn['id'].toString())
          : BigInt.from(0),

      name: jsonn['name'] != null ? jsonn['name'].toString() : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    BigInt? id,
    String? name,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (createdAt != null) 'created_at': createdAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      name: name,
      createdAt: createdAt,
    );
  }

  static const _unset = Object();
  Area copyWith({
    Object? id = _unset,
    Object? name = _unset,
    Object? createdAt = _unset,
  }) {
    return Area(
      id: id == _unset ? this.id : id as BigInt,
      name: name == _unset ? this.name : name as String?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
    );
  }
}
