// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'package:efs_misr/core/entities/branch_entity.dart';

import 'area.dart';
import 'supadart_header.dart';

class Branch implements SupadartClass<Branch> {
  final BigInt id;
  final BigInt? branchId;
  final String? name;
  final BigInt? area;
  final Area? areaObject;
  final DateTime createdAt;

  const Branch({
    required this.id,
    this.branchId,
    this.name,
    this.area,
    required this.areaObject,
    required this.createdAt,
  });

  static String get table_name => 'branch';
  static String get c_id => 'id';
  static String get c_branchId => 'branch_id';
  static String get c_name => 'name';
  static String get c_area => 'area';
  static String get c_createdAt => 'created_at';

  static List<Branch> converter(List<Map<String, dynamic>> data) {
    return data.map(Branch.fromJson).toList();
  }

  static Branch converterSingle(Map<String, dynamic> data) {
    return Branch.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    BigInt? id,
    BigInt? branchId,
    String? name,
    BigInt? area,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id.toString(),
      if (branchId != null) 'branch_id': branchId.toString(),
      if (name != null) 'name': name,
      if (area != null) 'area': area,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    BigInt? id,
    BigInt? branchId,
    String? name,
    BigInt? area,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      branchId: branchId,
      name: name,
      area: area,
      createdAt: createdAt,
    );
  }

  static Map<String, dynamic> update({
    BigInt? id,
    BigInt? branchId,
    String? name,
    BigInt? area,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      branchId: branchId,
      name: name,
      area: area,
      createdAt: createdAt,
    );
  }

  factory Branch.fromJson(Map<String, dynamic> jsonn) {
    final areaValue = jsonn['area'];

    BigInt? parsedAreaId;
    Area? parsedAreaObject;

    // إذا كانت الـ area رقم أو نص
    if (areaValue is int) {
      parsedAreaId = BigInt.from(areaValue);
    } else if (areaValue is String) {
      parsedAreaId = BigInt.tryParse(areaValue);
    }
    else if (areaValue is Map<String, dynamic>) {
    parsedAreaObject = Area.fromJson(areaValue);
    parsedAreaId = BigInt.from(areaValue['id'] ?? 0);
    }
    return Branch(
      id: jsonn['id'] != null
          ? BigInt.parse(jsonn['id'].toString())
          : BigInt.from(0),
      branchId: jsonn['branch_id'] != null
          ? BigInt.parse(jsonn['branch_id'].toString())
          : null,
      name: jsonn['name'] != null ? jsonn['name'].toString() : null,
      area:parsedAreaId,
      areaObject: parsedAreaObject,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    BigInt? id,
    BigInt? branchId,
    String? name,
    BigInt? area,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (branchId != null) 'branch_id': branchId,
      if (name != null) 'name': name,
      if (area != null) 'area': area,
      if (createdAt != null) 'created_at': createdAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      branchId: branchId,
      name: name,
      area: area,
      createdAt: createdAt,
    );
  }

  static const _unset = Object();
  Branch copyWith({
    Object? id = _unset,
    Object? branchId = _unset,
    Object? name = _unset,
    Object? area = _unset,
    Object? createdAt = _unset,
  }) {
    return Branch(
      id: id == _unset ? this.id : id as BigInt,
      branchId: branchId == _unset ? this.branchId : branchId as BigInt?,
      name: name == _unset ? this.name : name as String?,
      area: area == _unset ? this.area : area as BigInt?,
      areaObject: areaObject == _unset ? areaObject : areaObject,

      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
    );
  }

  BranchEntity toBranchEntity() {
    return BranchEntity(
      name: name ?? '',
      id: id.toInt(),
      areaId: area?.toInt() ?? 0,
    );
  }
}
