// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Attendance implements SupadartClass<Attendance> {
  final String id;
  final DateTime createdAt;
  final String image;
  final DateTime? checkIn;
  final DateTime? checkOut;
  final String location;
  final String userId;

  Attendance({
    required this.id,
    required this.createdAt,
    required this.image,
    required this.userId,
    required this.location,
    required this.checkIn,
    required this.checkOut,
  });

  static String get table_name => 'attendants';

  static String get c_id => 'id';

  static String get c_createdAt => 'created_at';

  static String get c_image => 'image';

  static String get c_userId => 'user_id';

  static String get c_location => 'location';

  static String get c_check_in => 'check_in';

  static String get c_check_out => 'check_out';

  static List<Attendance> converter(List<Map<String, dynamic>> data) {
    return data.map(Attendance.fromJson).toList();
  }

  static Attendance converterSingle(Map<String, dynamic> data) {
    return Attendance.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    DateTime? createdAt,
    required String image,
    required String userId,
    required String location,
    required DateTime? checkIn,
    required DateTime? checkOut,
  }) {
    return {
      if (id != null) 'id': id.toString(),
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (image != null) 'image': image,
      if (userId != null) 'user_id': userId,
      if (location != null) 'location': location,
      if (checkIn != null) 'check_in': checkIn.toIso8601String(),
      if (checkOut != null) 'check_out': checkOut.toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    DateTime? createdAt,
    required String image,
    required String userId,
    required String location,
    required DateTime? checkIn,
     DateTime? checkOut,
  }) {
    return _generateMap(
      id: id,
      createdAt: createdAt,
      image: image,
      userId: userId,
      location: location,
      checkIn: checkIn,
      checkOut: checkOut,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    DateTime? createdAt,
    required String image,
    required String userId,
    required String location,
     DateTime? checkIn,
     DateTime? checkOut,
  }) {
    return _generateMap(
      id: id,
      createdAt: createdAt,
      image: image,
      userId: userId,
      location: location,
      checkIn: checkIn,
      checkOut: checkOut,
    );
  }

  factory Attendance.fromJson(Map<String, dynamic> jsonn) {
    return Attendance(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      image: jsonn['image'] != null ? jsonn['image'].toString() : '',
      location: jsonn['location'] != null ? jsonn['location'].toString() : '',
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : '',
      checkIn: jsonn['check_in'] != null
          ? DateTime.parse(jsonn['check_in'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      checkOut: jsonn['check_out'] != null
          ? DateTime.parse(jsonn['check_out'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    DateTime? createdAt,
    required String image,
    required String userId,
    required String location,
    required DateTime? checkIn,
    required DateTime? checkOut,
  }) {
    return {
      if (id != null) 'id': id,
      if (createdAt != null) 'created_at': createdAt,
      if (image != null) 'image': image,
      if (userId != null) 'user_id': userId,
      if (location != null) 'location': location,
      if (checkIn != null) 'check_in': checkIn,
      if (checkOut != null) 'check_out': checkOut,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      createdAt: createdAt,
      image: image,
      location: location,
      checkIn: checkIn,
      checkOut: checkOut,
      userId: userId,
    );
  }

  Attendance copyWith({
    String? id,
    DateTime? createdAt,
    required String image,
    required String userId,
    required String location,
    required DateTime? checkIn,
    required DateTime? checkOut,
  }) {
    return Attendance(
      id: id ?? this.id,
      createdAt: createdAt ?? this.createdAt,
      image: image,
      userId: userId,
      checkOut: checkOut,
      checkIn: checkIn,
      location: location,
    );
  }
}
