// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class UsersStatus implements SupadartClass<UsersStatus> {
  final String id;
  final DateTime createdAt;
  final String? name;

  UsersStatus({required this.id, required this.createdAt, required this.name});

  static String get table_name => 'user_status';

  static String get c_id => 'id';

  static String get c_createdAt => 'created_at';

  static String get c_name => 'name';

  static List<UsersStatus> converter(List<Map<String, dynamic>> data) {
    return data.map(UsersStatus.fromJson).toList();
  }

  static UsersStatus converterSingle(Map<String, dynamic> data) {
    return UsersStatus.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    DateTime? createdAt,
    String? name,
  }) {
    return {
      if (id != null) 'id': id.toString(),
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (name != null) 'name': name,
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    DateTime? createdAt,
    String? name,
  }) {
    return _generateMap(id: id, createdAt: createdAt, name: name);
  }

  static Map<String, dynamic> update({
    String? id,
    DateTime? createdAt,
    String? name,
  }) {
    return _generateMap(id: id, createdAt: createdAt, name: name);
  }

  factory UsersStatus.fromJson(Map<String, dynamic> jsonn) {
    return UsersStatus(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      name: jsonn['name'] != null ? jsonn['name'].toString() : '',
    );
  }

  static Object New({String? id, DateTime? createdAt, String? name}) {
    return {
      if (id != null) 'id': id,
      if (createdAt != null) 'created_at': createdAt,
      if (name != null) 'username': name,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(id: id, createdAt: createdAt, name: name);
  }

  UsersStatus copyWith({String? id, DateTime? createdAt, String? name}) {
    return UsersStatus(
      id: id ?? this.id,
      createdAt: createdAt ?? this.createdAt,
      name: name ?? this.name,
    );
  }
}
